baseURL = "https://www.kezic.net/"
languageCode = "en-us"
title = "Darko Kezic's Blog"
theme = "dkeza-hyde"
googleAnalytics = "UA-138734051-1"

[params]
description = "Software engineer, coder, entrepreneur, passionate about new technologies in IT industry"
themeColor = "theme-base-0c"
copyright = "Darko Kezic. All rights reserved."
github = "https://github.com/dkeza"
use_icons = true