baseURL = "https://www.kezic.net/"
languageCode = "en-us"
title = "Darko Kezic's Blog"
theme = "dkeza-hyde"
googleAnalytics = "UA-138734051-1"
disqusShortname = "darko-kezic-blog"

[params]
description = "Software engineer, coder, entrepreneur, hiker"
themeColor = "theme-base-0c"
copyright = "Darko Kezic. All rights reserved."
github = "https://github.com/dkeza"
linkedin = "https://www.linkedin.com/in/darkokezic"
use_icons = true
mainSections = ["posts"]
staticpage = false
contactform = false